### ISSUE TITLE
ダメージを受ける床の音の再生について

### ISSUE THREAD

**Issue by tatsukawa** [Rikyu3/fire-fight#10]
多分，fps(1秒の間に表示されるフレーム数)回ずっと鳴らしているため，おかしなことになっている．

再生する音の長さ分だけ，待ってあげてから再び再生するということをしないといけない

**Comment by tatsukawa** [comment]
これ，kaidanというオブジェクトにイベントハンドラを登録してる(addEventListner)のが悪くて，knightが動いたときに，kaidanにintersectionしたなら音を鳴らす，ということをやった方がよさそう．

そうやると，敵オブジェクトに当たったときは止まる，みたいな処理も簡単に書ける

**Comment by Rikyu3** [comment]
できました
