### ISSUE TITLE
３番目の画面を作りたい

### ISSUE THREAD

**Issue by Rikyu3** [Rikyu3/fire-fight#5]
３番目のmapは作れているけど、繋げられない

**Comment by tatsukawa** [comment]
いろいろ方法はあるんですが，マップの状態を持つ変数を作るのが良いです．

``` js
var state = 0;
```

みたいな感じで，ステージ1が0, ステージ2が1, ステージ3が2...みたいな感じでstateを変化させます．

そして，

``` js
if(state == 0) {
    /* ステージ1の処理*/
} else if(state == 1) {
    /* ステージ2の処理*/
} else if(state == 2) {
    /* ステージ3の処理*/
}
```

みたいな感じで書いていくと各ステージ毎の処理が記述できて良いと思います．

ちなみに，stateは英語で状態という意味です．

**Comment by Rikyu3** [comment]
できました
ありがとうございます
