### ISSUE TITLE
2画面に入ると音楽と一緒に雑音が入る

### ISSUE THREAD

**Issue by Rikyu3** [Rikyu3/fire-fight#6]
バリバリという変な音がします。

**Comment by tatsukawa** [comment]
これちょっとムズイので説明すると，

https://github.com/Rikyu3/fire-fight/blob/master/main.js#L385-L408

この部分の

``` js
kaidan.addEventListener("enterframe", function() {
     /* 中略 */
  }
});
```

は，kaidanのフレーム(領域)に入ると，`function() { }`を実行するように設定する，ということを示しています．

今何が問題になっているかというと，階段にenterframeして，マップが変わってからしばらく放置していても，ずっとenterframeが呼び出され，knightがこのkaidanにintersectされているので，ずっとfuction() { }が呼び出されます．そして，呼び出している関数では，kowai.mp3をずっとcloneしているので，凄い数のkowai.mp3が少しずれながら再生しているという状況になっています．

解決方法はいくらか考えられますが，少し考えてみてください．

**Comment by Rikyu3** [comment]
kaidanスプライトの['kowai.mp3'].loop;
のところのloopを消してずっとループさせないようにするとできました。

**Comment by tatsukawa** [comment]
本当にそれで出来ていますか？

**Comment by Rikyu3** [comment]
できました
ありがとうございます
