### ISSUE TITLE
音楽を繰り返し流したい

### ISSUE THREAD

**Issue by Rikyu3** [Rikyu3/fire-fight#8]
画面が終わらないうちに曲が終わってしまう

**Comment by tatsukawa** [comment]
Google検索の能力も身につけましょう．必要なキーワードを入れて検索すると，欲しい情報が結構得られます．（といっても公式Documentを見るのが一番いいですが）

今回だと，`enchant.js BGM ループ`みたいな感じで検索すると引っかかります．

**Comment by Rikyu3** [comment]
できました。

**Comment by tatsukawa** [comment]
確認してみたんですが，自分の環境では，BGMが鳴ってないですね．

**Comment by tatsukawa** [comment]
あと，これ結局そのページ開いていないとループ再生されないのでちょっとダメですね．

**Comment by tatsukawa** [comment]
ローカル環境にWebサーバを立てる方法はたくさん記事があるし，それ見てもらえれば早いんですが，Mac使っているんだったらApacheが既に入っているので，それを使えば良いです．
